/* Vulnerable Extension Lists */

DROP TABLE IF EXISTS `#__jed_vel_report`;
CREATE TABLE IF NOT EXISTS `#__jed_vel_report`
(
	`id`                               INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`reporter_fullname`                VARCHAR(255) NOT NULL DEFAULT '',
	`reporter_email`                   VARCHAR(255) NOT NULL DEFAULT '',
	`reporter_organisation`            VARCHAR(255) NOT NULL DEFAULT '',
	`pass_details_ok`                  INT          NOT NULL DEFAULT '0',
	`vulnerability_type`               INT          NOT NULL DEFAULT '0',
	`vulnerable_item_name`             VARCHAR(255) NOT NULL DEFAULT '',
	`vulnerable_item_version`          VARCHAR(255) NOT NULL DEFAULT '',
	`exploit_type`                     INT          NOT NULL DEFAULT '0',
	`exploit_other_description`        TEXT         NOT NULL,
	`vulnerability_description`        TEXT         NOT NULL,
	`vulnerability_how_found`          TEXT         NOT NULL,
	`vulnerability_actively_exploited` INT          NOT NULL DEFAULT '0',
	`vulnerability_publicly_available` INT          NOT NULL DEFAULT '0',
	`vulnerability_publicly_url`       VARCHAR(255) NOT NULL DEFAULT '',
	`vulnerability_specific_impact`    TEXT         NOT NULL,
	`developer_communication_type`     INT          NOT NULL DEFAULT '0',
	`developer_patch_download_url`     VARCHAR(255) NOT NULL DEFAULT '',
	`developer_name`                   VARCHAR(255) NOT NULL DEFAULT '',
	`developer_contact_email`          VARCHAR(255) NOT NULL DEFAULT '',
	`tracking_db_name`                 VARCHAR(255) NOT NULL DEFAULT '',
	`tracking_db_id`                   VARCHAR(255) NOT NULL DEFAULT '',
	`jed_url`                          VARCHAR(255) NOT NULL DEFAULT '',
	`developer_additional_info`        TEXT         NOT NULL,
	`download_url`                     VARCHAR(255) NOT NULL DEFAULT '',
	`consent_to_process`               INT          NOT NULL DEFAULT '0',
	`passed_to_vel`                    INT          NOT NULL DEFAULT '0',
	`vel_item_id`                      INT          NOT NULL DEFAULT '0',
	`data_source`                      INT          NOT NULL DEFAULT '0',
	`date_submitted`                   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`user_ip`                          VARCHAR(20)  NOT NULL DEFAULT '',
	`created_by`                       INT          NOT NULL DEFAULT '0',
	`modified_by`                      INT          NOT NULL DEFAULT '0',
	`created`                          DATETIME,
	`modified`                         DATETIME,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `#__jed_vel_developer_update`;
CREATE TABLE IF NOT EXISTS `#__jed_vel_developer_update`
(
	`id`                      int unsigned NOT NULL AUTO_INCREMENT,
	`contact_fullname`        varchar(255) NOT NULL DEFAULT '',
	`contact_organisation`    varchar(255) NOT NULL DEFAULT '',
	`contact_email`           varchar(255) NOT NULL DEFAULT '',
	`vulnerable_item_name`    varchar(255) NOT NULL DEFAULT '',
	`vulnerable_item_version` varchar(255) NOT NULL DEFAULT '',
	`extension_update`        text         NOT NULL,
	`new_version_number`      varchar(255) NOT NULL DEFAULT '',
	`update_notice_url`       varchar(255) NOT NULL DEFAULT '',
	`changelog_url`           varchar(255) NOT NULL DEFAULT '',
	`download_url`            varchar(255) NOT NULL DEFAULT '',
	`consent_to_process`      int                   DEFAULT '0',
	`vel_item_id`             int          NOT NULL DEFAULT '0',
	`update_data_source`      int          NOT NULL DEFAULT '0',
	`update_date_submitted`   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update_user_ip`          varchar(20)  NOT NULL DEFAULT '',
	`created_by`              int          NOT NULL DEFAULT '0',
	`modified_by`             int          NOT NULL DEFAULT '0',
	`created`                 datetime,
	`modified`                datetime,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `#__jed_vel_abandoned_report`;
CREATE TABLE IF NOT EXISTS `#__jed_vel_abandoned_report`
(
	`id`                    int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`reporter_fullname`     VARCHAR(255)     NOT NULL,
	`reporter_email`        VARCHAR(255)     NOT NULL,
	`reporter_organisation` VARCHAR(255)     NULL     DEFAULT '',
	`extension_name`        VARCHAR(255)     NOT NULL,
	`developer_name`        VARCHAR(255)     NULL     DEFAULT '',
	`extension_version`     VARCHAR(255)     NULL     DEFAULT '',
	`extension_url`         VARCHAR(255)     NULL     DEFAULT '',
	`abandoned_reason`      TEXT             NULL,
	`consent_to_process`    VARCHAR(255)     NOT NULL DEFAULT '0',
	`passed_to_vel`         VARCHAR(255)     NULL     DEFAULT '0',
	`vel_item_id`           INT              NULL     DEFAULT 0,
	`data_source`           VARCHAR(255)     NULL     DEFAULT '0',
	`date_submitted`        DATETIME         NULL     DEFAULT CURRENT_TIMESTAMP,
	`user_ip`               VARCHAR(20)      NULL     DEFAULT '',
	`created_by`            INT(11)          NULL     DEFAULT 0,
	`modified_by`           INT(11)          NULL     DEFAULT 0,
	`created`               DATETIME,
	`modified`              DATETIME,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `#__jed_vel_vulnerable_item`;
CREATE TABLE IF NOT EXISTS `#__jed_vel_vulnerable_item`
(
	`id`                        int unsigned  NOT NULL AUTO_INCREMENT,
	`vulnerable_item_name`      varchar(255)  NOT NULL DEFAULT '',
	`vulnerable_item_version`   varchar(255)  NOT NULL DEFAULT '',
	`title`                     varchar(255)  NOT NULL DEFAULT '',
	`internal_description`      text          NOT NULL,
	`status`                    int           NOT NULL DEFAULT '0',
	`report_id`                 int           NOT NULL DEFAULT '-1',
	`jed`                       varchar(255)  NOT NULL DEFAULT '',
	`risk_level`                varchar(255)  NOT NULL DEFAULT '',
	`start_version`             varchar(255)  NOT NULL DEFAULT '',
	`vulnerable_version`        varchar(255)  NOT NULL DEFAULT '',
	`patch_version`             varchar(255)  NOT NULL DEFAULT '',
	`recommendation`            varchar(255)  NOT NULL DEFAULT '',
	`update_notice`             varchar(255)  NOT NULL DEFAULT '',
	`exploit_type`              int           NOT NULL DEFAULT '0',
	`exploit_other_description` text          NOT NULL,
	`xml_manifest`              text          NOT NULL,
	`manifest_location`         varchar(255)  NOT NULL DEFAULT '',
	`install_data`              varchar(255)  NOT NULL DEFAULT '',
	`discovered_by`             varchar(255)  NOT NULL DEFAULT '',
	`discoverer_public`         varchar(255)  NOT NULL DEFAULT '',
	`fixed_by`                  varchar(255)  NOT NULL DEFAULT '',
	`coordinated_by`            varchar(255)  NOT NULL DEFAULT '',
	`jira`                      varchar(255)  NOT NULL DEFAULT '',
	`cve_id`                    varchar(255)  NOT NULL DEFAULT '',
	`cwe_id`                    varchar(255)  NOT NULL DEFAULT '',
	`cvssthirty_base`           varchar(255)  NOT NULL DEFAULT '',
	`cvssthirty_base_score`     decimal(5, 2) NOT NULL DEFAULT '0.00',
	`cvssthirty_temp`           varchar(255)  NOT NULL DEFAULT '',
	`cvssthirty_temp_score`     decimal(5, 2) NOT NULL DEFAULT '0.00',
	`cvssthirty_env`            varchar(255)  NOT NULL DEFAULT '',
	`cvssthirty_env_score`      decimal(5, 2) NOT NULL DEFAULT '0.00',
	`public_description`        text          NOT NULL,
	`alias`                     varchar(255)  NOT NULL DEFAULT '',
	`created_by`                int           NOT NULL DEFAULT '0',
	`modified_by`               int           NOT NULL DEFAULT '0',
	`created`                   datetime,
	`modified`                  datetime,
	`checked_out`               int unsigned,
	`checked_out_time`          datetime,
	`state`                     tinyint       NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
